@startuml
'https://plantuml.com/sequence-diagram
class Application{
    start(Stage)
    main(String[])
}

class ApplicationController{
    -itemDescription
    -dueDate
    -itemName
    -editSelected
    -newEmptyListButtonPressed()
    -saveAsButtonPressed()
    -saveButtonPressed()
    -editSelectedButtonPressed()
    -viewAllButtonPressed()
    -viewCompletedButtonPressed()
    -viewIncompleteButtonPressed()
    -loadButtonPressed()
    -deleteListButtonPressed()
    -lowerTable()
    +initialize()
}

Application --o ApplicationController

Class AddDeleteItem{
    +AddDeleteItem(String, String, String)
    +addItem():String[]
    +removeItem()
    +getComplete()
    +getDue()
    +getName()
    +getDescription()
}

ApplicationController --o AddDeleteItem

Class FileIO{
    +FileIO()
    +filePrep():String
    +saveFile()
    +specifyFileLocation()
    +loadList()
}

ApplicationController --o FileIO

Class FormatList{
    +FormatList()
    +displayList()
    +clearList()
}

ApplicationController --o FormatList

Class ParseTyping{
    +enforceDateFormat():boolean
    +enforceTitleCharCount():boolean
    +isGregorian()
}

ApplicationController --o ParseTyping

@enduml